In [2]:
import pandas as pd

## Membaca CSV di Python dengan Pandas

In [3]:
file = "../0.Dataset/people_data.csv"
df = pd.read_csv(file)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,NaN,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

### Fitur-fitur dalam Pandas read_csv

### 1. Baca kolom tertentu menggunakan read_csv

In [4]:
df = pd.read_csv(file,usecols=['First Name','Email'])
df

  First Name                       Email
0     Shelby        elijah57@example.net
1    Phillip       bethany14@example.com
2   Kristine       bthompson@example.com
3    Yesenia   kaitlinkaiser@example.com
4       Lori  buchananmanuel@example.net

### 2. Mengatur Kolom Indeks (index_col)

In [5]:
df = pd.read_csv(file,index_col='First Name')
df

,Last Name,Sex,Email,Date of birth,Job Title
First Name,,,,,
Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
Lori,Todd,NaN,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

### 3. Menangani Nilai yang Hilang Menggunakan read_cs

In [6]:
df = pd.read_csv(file,na_values=["N/A"])
df # gk bisa

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,NaN,buchananmanuel@example.net,1938-12-01,Veterinary surgeon

### 4. Membaca File CSV dengan Pembatas yang Berbeda

In [9]:
df = pd.read_csv('../0.Dataset/sample_bill.csv',sep='[:,|_]',engine='python')
df

   totalbill   tip      sex smoker   day     time   size
0      16.99  1.01   Female     No   Sun   Dinner      2
1      10.34  1.66     Male     No   Sun   Dinner      3
2      21.01  3.50     Male     No   Sun   Dinner      3
3      23.68  3.31     Male     No   Sun   Dinner      2
4      24.59  3.61   Female     No   Sun   Dinner      4
5      25.29  4.71     Male     No   Sun   Dinner      4

### 5. membatasi jumlah baris yang dibaca

In [10]:
df = pd.read_csv(file,nrows=3)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath

### 6. melewati baris yang tidak perlu di awal file,

In [11]:
df = pd.read_csv(file)
print(f"Previous Dataset:\n {df}")

df = pd.read_csv(file,skiprows=[4,5])
print(f"Datasrt Sfter skipping  rows:\n {df}")

Previous Dataset:
   First Name Last Name     Sex                       Email Date of birth  \
0     Shelby   Terrell    Male        elijah57@example.net    1945-10-26
1    Phillip   Summers  Female       bethany14@example.com    1910-03-24
2   Kristine    Travis    Male       bthompson@example.com    1992-07-02
3    Yesenia  Martinez    Male   kaitlinkaiser@example.com    2017-08-03
4       Lori      Todd     NaN  buchananmanuel@example.net    1938-12-01

            Job Title
0     Games developer
1      Phytotherapist
2           Homeopath
3   Market researcher
4  Veterinary surgeon
Datasrt Sfter skipping  rows:
   First Name Last Name     Sex                  Email Date of birth  \
0     Shelby   Terrell    Male   elijah57@example.net    1945-10-26
1    Phillip   Summers  Female  bethany14@example.com    1910-03-24
2   Kristine    Travis    Male  bthompson@example.com    1992-07-02

         Job Title
0  Games developer
1   Phytotherapist
2        Homeopath

### 7. Mengurai Tanggal (parse_dates)

In [15]:
df = pd.read_csv(file,parse_dates=['Date of birth'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   First Name     5 non-null      object
 1   Last Name      5 non-null      object
 2   Sex            4 non-null      object
 3   Email          5 non-null      object
 4   Date of birth  5 non-null      datetime64[ns]
 5   Job Title      5 non-null      object
dtypes: datetime64[ns](1), object(5)
memory usage: 372.0+ bytes

### 8. Memuat Data CSV dari URL

In [16]:
url = "https://media.geeksforgeeks.org/wp-content/uploads/20241121154629307916/people_data.csv"
df = pd.read_csv(url)
df

,First Name,Last Name,Sex,Email,Date of birth,Job Title
0,Shelby,Terrell,Male,elijah57@example.net,1945-10-26,Games developer
1,Phillip,Summers,Female,bethany14@example.com,1910-03-24,Phytotherapist
2,Kristine,Travis,Male,bthompson@example.com,1992-07-02,Homeopath
3,Yesenia,Martinez,Male,kaitlinkaiser@example.com,2017-08-03,Market researcher
4,Lori,Todd,Male,buchananmanuel@example.net,1938-12-01,Veterinary surgeon