In [2]:
import pandas as pd

### 1.membaca FIle Excel

In [4]:
file = '../0.Dataset/data_gaji.xlsx'
df = pd.read_excel(file)
df

  Id_Karyawan  Departemen  Pengalaman_Kerja Pendidikan  Gaji_Bulanan
0        K001          IT                 3         S1       8500000
1        K002          HR                 5         S1       9200000
2        K003     Finance                 2         S1       7800000
3        K004   Marketing                 7         S2      12500000
4        K005          IT                 1         D3       5500000
5        K006  Operations                 4         S1       8000000
6        K007     Finance                 9         S2      15000000
7        K008          HR                 2        NaN       6000000
8        K009          IT                 6         S1      11000000
9        K010   Marketing                 3         S1       8200000

### 2.  Untuk memilih kolom tertentu

In [7]:
df = pd.read_excel(file,index_col = 0)  

print(df)

             Departemen  Pengalaman_Kerja Pendidikan  Gaji_Bulanan
Id_Karyawan
K001                 IT                 3         S1       8500000
K002                 HR                 5         S1       9200000
K003            Finance                 2         S1       7800000
K004          Marketing                 7         S2      12500000
K005                 IT                 1         D3       5500000
K006         Operations                 4         S1       8000000
K007            Finance                 9         S2      15000000
K008                 HR                 2        NaN       6000000
K009                 IT                 6         S1      11000000
K010          Marketing                 3         S1       8200000

### 3. membuat data tanpa nama colom

In [9]:
df = pd.read_excel(file,header=None)
df

              0           1                 2           3             4
0   Id_Karyawan  Departemen  Pengalaman_Kerja  Pendidikan  Gaji_Bulanan
1          K001          IT                 3          S1       8500000
2          K002          HR                 5          S1       9200000
3          K003     Finance                 2          S1       7800000
4          K004   Marketing                 7          S2      12500000
5          K005          IT                 1          D3       5500000
6          K006  Operations                 4          S1       8000000
7          K007     Finance                 9          S2      15000000
8          K008          HR                 2         NaN       6000000
9          K009          IT                 6          S1      11000000
10         K010   Marketing                 3          S1       8200000

### 4. Mengubah Tipe pada sebuah kolom

In [12]:
df = pd.read_excel(file,dtype={'Pengalaman_Kerja':str,'Gaji_Bulanan':float})
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Id_Karyawan       10 non-null     object
 1   Departemen        10 non-null     object
 2   Pengalaman_Kerja  10 non-null     object
 3   Pendidikan        9 non-null      object
 4   Gaji_Bulanan      10 non-null     float64
dtypes: float64(1), object(4)
memory usage: 532.0+ bytes

#### 5. mengubah data kosong jadi NAN

In [ ]:
df = pd.read_excel(file,na_values=['HR']) #anghap 'HR' nilai anomali makanya diubah jadi NaN
df

  Id_Karyawan  Departemen  Pengalaman_Kerja Pendidikan  Gaji_Bulanan
0        K001          IT                 3         S1       8500000
1        K002         NaN                 5         S1       9200000
2        K003     Finance                 2         S1       7800000
3        K004   Marketing                 7         S2      12500000
4        K005          IT                 1         D3       5500000
5        K006  Operations                 4         S1       8000000
6        K007     Finance                 9         S2      15000000
7        K008         NaN                 2        NaN       6000000
8        K009          IT                 6         S1      11000000
9        K010   Marketing                 3         S1       8200000