In [2]:
import pandas as pd
import numpy as np

## Memeriksa Nilai yang Hilang di Pandas

### 1. Menggunakan isnull()

In [ ]:
# 1. Menemukan Nilai yang Hilang dalam DataFrame
data = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
df = pd.DataFrame(data)
mv = df.isnull()
print(mv)

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [9]:
# 2.  Menemukan Nilai yang Hilang dalam DataFrame
data = pd.read_csv('../0.Dataset/employees.csv')
bool_series = pd.isnull(data['First Name'])
missing_gender_data = data[bool_series]
print(missing_gender_data)

    First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
7          NaN  Female  7/20/2015        10:43 AM   45906   11.598
23         NaN    Male  6/14/2012         4:19 PM  125792    5.042
25         NaN    Male  10/8/2012         1:12 AM   37076   18.576
32         NaN    Male  8/21/1998         2:27 PM  122340    6.417
39         NaN    Male  1/29/2016         2:33 AM  122173    7.797
..         ...     ...        ...             ...     ...      ...
902        NaN    Male  5/23/2001         7:52 PM  103877    6.322
925        NaN  Female  8/23/2000         4:19 PM   95866   19.388
946        NaN  Female  9/15/1985         1:50 AM  133472   16.941
947        NaN    Male  7/30/2012         3:07 PM  107351    5.329
951        NaN  Female  9/14/2010         5:19 AM  143638    9.662

    Senior Management             Team
7                 NaN          Finance
23                NaN              NaN
25                NaN  Client Services
32                NaN              NaN
39                NaN  Client Services
..                ...              ...
902               NaN     Distribution
925               NaN            Sales
946               NaN     Distribution
947               NaN        Marketing
951               NaN              NaN

[67 rows x 8 columns]

### 2. Menggunakan isna()

In [11]:
data = {'Name': ['Amit', 'Sita', np.nan, 'Raj'],
        'Age': [25, np.nan, 22, 28]}

df = pd.DataFrame(data)

print(df.isna())

    Name    Age
0  False  False
1  False   True
2   True  False
3  False  False

### 3. Memeriksa Nilai yang Tidak Hilang Menggunakan notnull()

In [ ]:
# 1. Mengidentifikasi Nilai yang Tidak Hilang dalam DataFrame
ata = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}

df = pd.DataFrame(data)
Non_missingValue = df.notnull()

print(Non_missingValue)

   First Score  Second Score  Third Score
0         True          True        False
1         True          True         True
2        False          True         True
3         True         False         True

In [14]:
# 2. Memfilter Data dengan Nilai yang Tidak Hilang
data = pd.read_csv('../0.Dataset/employees.csv')
notnull = pd.notnull(data['Gender'])

gender_notnull = data.loc[notnull]
print(gender_notnull)

    First Name  Gender Start Date Last Login Time  Salary  Bonus %  \
0      Douglas    Male   8/6/1993        12:42 PM   97308    6.945
1       Thomas    Male  3/31/1996         6:53 AM   61933    4.170
2        Maria  Female  4/23/1993        11:17 AM  130590   11.858
3        Jerry    Male   3/4/2005         1:00 PM  138705    9.340
4        Larry    Male  1/24/1998         4:47 PM  101004    1.389
..         ...     ...        ...             ...     ...      ...
994     George    Male  6/21/2013         5:47 PM   98874    4.479
996    Phillip    Male  1/31/1984         6:30 AM   42392   19.675
997    Russell    Male  5/20/2013        12:39 PM   96914    1.421
998      Larry    Male  4/20/2013         4:45 PM   60500   11.985
999     Albert    Male  5/15/2012         6:24 PM  129949   10.169

    Senior Management                  Team
0                True             Marketing
1                True                   NaN
2               False               Finance
3                True               Finance
4                True       Client Services
..                ...                   ...
994              True             Marketing
996             False               Finance
997             False               Product
998             False  Business Development
999              True                 Sales

[855 rows x 8 columns]

## Mengisi Nilai yang Hilang di Pandas

### 1. Menggunakan fillna()

In [ ]:
# 1. isi Nilai yang Hilang dengan Nol
data = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}

df = pd.DataFrame(data)
df= df.fillna(0)
print(df)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [23]:
# 2. Isi dengan Nilai Sebelumnya (Isi Maju)
data = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}

df = pd.DataFrame(data)
df= df.ffill()
print(df)

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [26]:
# 3. Isi dengan Nilai Berikutnya (Isi Mundur)
data = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}

df = pd.DataFrame(data)
df= df.bfill()
print(df)

   First Score  Second Score  Third Score
0        100.0          30.0         40.0
1         90.0          45.0         40.0
2         95.0          56.0         80.0
3         95.0           NaN         98.0

In [29]:
# 4. Isi Nilai NaN dengan 'Tidak Ada Jenis Kelamin'
data = pd.read_csv('../0.Dataset/employees.csv')
data= data[10:25]

data['Gender'] = data['Gender'].fillna('No Gender')
data

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,NaN
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,No Gender,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,No Gender,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,NaN,Male,6/14/2012,4:19 PM,125792,5.042,NaN,NaN
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services

### 2. Menggunakan replace()
Gunakan fungsi replace() untuk mengganti nilai NaN dengan nilai tertentu.

In [35]:
data = pd.read_csv('../0.Dataset/employees.csv')

data = data.replace(to_replace=np.nan,value=-999)
data[10:25]

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
10,Louise,Female,8/12/1980,9:01 AM,63241,15.132,True,-999
11,Julie,Female,10/26/1997,3:19 PM,102508,12.637,True,Legal
12,Brandon,Male,12/1/1980,1:08 AM,112807,17.492,True,Human Resources
13,Gary,Male,1/27/2008,11:40 PM,109831,5.831,False,Sales
14,Kimberly,Female,1/14/1999,7:13 AM,41426,14.543,True,Finance
15,Lillian,Female,6/5/2016,6:09 AM,59414,1.256,False,Product
16,Jeremy,Male,9/21/2010,5:56 AM,90370,7.369,False,Human Resources
17,Shawn,Male,12/7/1986,7:45 PM,111737,6.414,False,Product
18,Diana,Female,10/23/1981,10:27 AM,132940,19.082,False,Client Services
19,Donna,Female,7/22/2010,3:48 AM,81014,1.894,False,Product
20,Lois,-999,4/22/1995,7:18 PM,64714,4.934,True,Legal
21,Matthew,Male,9/5/1995,2:12 AM,100612,13.645,False,Marketing
22,Joshua,-999,3/8/2012,1:58 AM,90816,18.816,True,Client Services
23,-999,Male,6/14/2012,4:19 PM,125792,5.042,-999,-999
24,John,Male,7/1/1992,10:08 PM,97950,13.873,False,Client Services

### 3. Menggunakan interpolate()
Fungsi interpolate() mengisi nilai yang hilang menggunakan teknik interpolasi seperti metode linier.

In [39]:
df = pd.DataFrame({"A": [12, 4, 5, None, 1], 
                   "B": [None, 2, 54, 3, None], 
                   "C": [20, 16, None, 3, 8], 
                   "D": [14, 3, None, None, 6]})  
print(f"Sebelum:\n {df}")
df = df.interpolate(method='linear',limit_direction='forward')
print(f"Sesudah:\n {df}")

Sebelum:
       A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0
Sesudah:
       A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   4.0
3   3.0   3.0   3.0   5.0
4   1.0   3.0   8.0   6.0

### Menghapus Nilai yang Hilang di Pandas