In [71]:
import pandas as pd
import numpy as np

## Membagi Data ke dalam Kelompok

### 1. Mengelompokkan data berdasarkan satu kunci

In [72]:
data1 = {'Name':['Jai', 'Anuj', 'Jai', 'Princi',
                 'Gaurav', 'Anuj', 'Princi', 'Abhi'],
        'Age':[27, 24, 22, 32,
               33, 36, 27, 32],
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj',
                   'Jaunpur', 'Kanpur', 'Allahabad', 'Aligarh'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd',
                         'B.Tech', 'B.com', 'Msc', 'MA']}
df = pd.DataFrame(data1)
print(df)
print(df.groupby('Name').groups)

#mencetak entri pertama di semua grup
groub = df.groupby('Name')
groub.first()

     Name  Age    Address Qualification
0     Jai   27     Nagpur           Msc
1    Anuj   24     Kanpur            MA
2     Jai   22  Allahabad           MCA
3  Princi   32    Kannuaj           Phd
4  Gaurav   33    Jaunpur        B.Tech
5    Anuj   36     Kanpur         B.com
6  Princi   27  Allahabad           Msc
7    Abhi   32    Aligarh            MA
{'Abhi': [7], 'Anuj': [1, 5], 'Gaurav': [4], 'Jai': [0, 2], 'Princi': [3, 6]}

        Age  Address Qualification
Name
Abhi     32  Aligarh            MA
Anuj     24   Kanpur            MA
Gaurav   33  Jaunpur        B.Tech
Jai      27   Nagpur           Msc
Princi   32  Kannuaj           Phd

### 2. Mengelompokkan data dengan beberapa kunci

In [73]:
groub = df.groupby(['Name','Qualification'])
print(df.groupby(['Name','Qualification']).groups)

groub.first()

{('Abhi', 'MA'): [7], ('Anuj', 'B.com'): [5], ('Anuj', 'MA'): [1], ('Gaurav', 'B.Tech'): [4], ('Jai', 'MCA'): [2], ('Jai', 'Msc'): [0], ('Princi', 'Msc'): [6], ('Princi', 'Phd'): [3]}

                      Age    Address
Name   Qualification
Abhi   MA              32    Aligarh
Anuj   B.com           36     Kanpur
       MA              24     Kanpur
Gaurav B.Tech          33    Jaunpur
Jai    MCA             22  Allahabad
       Msc             27     Nagpur
Princi Msc             27  Allahabad
       Phd             32    Kannuaj

### 3.Mengelompokkan data berdasarkan kunci pengurutan

In [74]:
df.groupby('Name',sort=False)['Age'].sum()
#sorft=false => urut dari terkecil

Name
Jai       49
Anuj      60
Princi    59
Gaurav    33
Abhi      32
Name: Age, dtype: int64

### 4. Pengelompokan data dengan atribut objek

In [75]:
df.groupby('Name').groups

{'Abhi': [7], 'Anuj': [1, 5], 'Gaurav': [4], 'Jai': [0, 2], 'Princi': [3, 6]}

### 5. Melakukan iterasi melalui grup

In [76]:
grp = df.groupby('Name')

for name,groub in grp:
    print(name)
    print(groub)
    print(" ")

Abhi
   Name  Age  Address Qualification
7  Abhi   32  Aligarh            MA

Anuj
   Name  Age Address Qualification
1  Anuj   24  Kanpur            MA
5  Anuj   36  Kanpur         B.com

Gaurav
     Name  Age  Address Qualification
4  Gaurav   33  Jaunpur        B.Tech

Jai
  Name  Age    Address Qualification
0  Jai   27     Nagpur           Msc
2  Jai   22  Allahabad           MCA

Princi
     Name  Age    Address Qualification
3  Princi   32    Kannuaj           Phd
6  Princi   27  Allahabad           Msc

### 6. Memilih grup: dengan GroupBy.get_group()

In [77]:
grp = df.groupby(['Name','Address'])
output = grp.get_group(('Jai','Nagpur'))

print(output)

  Name  Age Address Qualification
0  Jai   27  Nagpur           Msc

## Menerapkan Fungsi pada Grup

### 1. Agregasi

In [78]:
grp1 = df.groupby(['Name'])
hasil = grp1['Age'].aggregate(['sum','mean','std'])
hasil

        sum  mean       std
Name
Abhi     32  32.0       NaN
Anuj     60  30.0  8.485281
Gaurav   33  33.0       NaN
Jai      49  24.5  3.535534
Princi   59  29.5  3.535534

### 2. Transformasi

In [107]:
data2 = {'Name':['Jai', 'Anuj', 'Jai', 'Princi', 
                 'Gaurav', 'Anuj', 'Princi', 'Abhi'], 
        'Age':[27, 24, 22, 32, 
               33, 36, 27, 32], 
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj',
                   'Jaunpur', 'Kanpur', 'Allahabad', 'Aligarh'], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd',
                         'B.Tech', 'B.com', 'Msc', 'MA'],
        'Score':[23, 34, 35, 45, 47, 50, 52, 53]} 

df2 = pd.DataFrame(data2)
grp2 = df2.groupby('Name')
func = lambda x : (x-x.mean()/x.std())
df2['Score']= grp2['Score'].transform(func)
grp2.first()

        Age  Address Qualification      Score
Name
Abhi     32  Aligarh            MA        NaN
Anuj     24   Kanpur            MA  30.287689
Gaurav   33  Jaunpur        B.Tech        NaN
Jai      27   Nagpur           Msc  19.582317
Princi   32  Kannuaj           Phd  35.201520

### 3. Filtrasi

In [104]:
grp2 = df2.groupby('Name')
grp.filter(lambda x : len (x) >= 2) # filter jumlah kemunculan berdasarkan 'Name'

   Name  Age Address Qualification
1  Anuj   24  Kanpur            MA
5  Anuj   36  Kanpur         B.com