In [209]:
import pandas as pd

### 1. Creating Dataframes

In [210]:
data={
    'Name':['Player_A','Player_B','Player_C'],
    'Age':[25,30,25]
}
df = pd.DataFrame(data)
print(df)

       Name  Age
0  Player_A   25
1  Player_B   30
2  Player_C   25

### 2. Creating Seriess

In [211]:
age_series = pd.Series([25,39,20],index=['Player_A','Player_B','Player_C'])
print(age_series)

Player_A    25
Player_B    39
Player_C    20
dtype: int64

### 3. Membaca FIle CSV dan JSON

In [212]:
#CSV FIlE
df_csv = pd.read_csv('../0.Dataset/people_data.csv')
print(df_csv)

  First Name Last Name     Sex                       Email Date of birth  \
0     Shelby   Terrell    Male        elijah57@example.net    1945-10-26
1    Phillip   Summers  Female       bethany14@example.com    1910-03-24
2   Kristine    Travis    Male       bthompson@example.com    1992-07-02
3    Yesenia  Martinez    Male   kaitlinkaiser@example.com    2017-08-03
4       Lori      Todd    Male  buchananmanuel@example.net    1938-12-01

            Job Title
0     Games developer
1      Phytotherapist
2           Homeopath
3   Market researcher
4  Veterinary surgeon

In [213]:
#JSON FILE
df_json = pd.read_csv('../0.Dataset/salary_rice.json')
print(df_json)

                                                                                                 [
  {"id": 1 "employee_name": "Budi Santoso" "salary_rice_kg": 10 "allowance_value_idr": 150000} NaN
  {"id": 2 "employee_name": "Siti Rahma"   "salary_rice_kg": 20 "allowance_value_idr": 300000} NaN
  {"id": 3 "employee_name": "Ahmad Dani"   "salary_rice_kg": 10 "allowance_value_idr": 150000} NaN
  {"id": 4 "employee_name": "Dewi Lestari" "salary_rice_kg": 25 "allowance_value_idr": 375000} NaN
]          NaN                             NaN                  NaN                            NaN

### 4. Memahami dan Menganalisis Kerangka Data

In [214]:
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
        'Age': [24, 27, 22, 32, 29],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix']}
df = pd.DataFrame(data)

print("Ambil 3 baris pertama dengan head(): ")
print(df.head(3))
 
print("\nAmbil 3 baris terkhir tail(): ")
print(df.tail(3))

print("\nMeringkas dataset dengan info(): ")
print(df.info())

print("\nmeringkas Statitika Deskriptif dengan describe(): ")
df.describe()

Ambil 3 baris pertama dengan head():
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago

Ambil 3 baris terkhir tail():
      Name  Age     City
2  Charlie   22  Chicago
3    David   32  Houston
4      Eva   29  Phoenix

Meringkas dataset dengan info():
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
dtypes: int64(1), object(2)
memory usage: 252.0+ bytes
None

meringkas Statitika Deskriptif dengan describe():

             Age
count   5.000000
mean   26.800000
std     3.962323
min    22.000000
25%    24.000000
50%    27.000000
75%    29.000000
max    32.000000

### 5. Pengindeksan di Pandas

In [215]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],'Age': [25, 30, 35]}
df = pd.DataFrame(data,index=['a','b','c'])

age_column = df['Age']
print(age_column)

a    25
b    30
c    35
Name: Age, dtype: int64

In [216]:
row_by_label = df.loc['b']
row_by_position = df.iloc[1]

print(f"Row by Label:\n {row_by_label}")
print(f"\nRow by Position:\n {row_by_position}")

Row by Label:
 Name    Bob
Age      30
Name: b, dtype: object

Row by Position:
 Name    Bob
Age      30
Name: b, dtype: object

### 6. Memilih dan Memfilter Data Berdasarkan Kondisi

In [217]:
data = {'Name': ['Alice', 'Bob', 'Charlie'],'Age': [25, 30, 35]}
df = pd.DataFrame(data)

filtered_df = df[df['Age'] > 29]
print(filtered_df)

      Name  Age
1      Bob   30
2  Charlie   35

### 7. Menangani Baris dan Kolom dalam Pandas DataFrame

In [218]:
# 1. Menambahkan Kolom Baru ke DataFrame :
df = pd.DataFrame({'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]})

df['Salary'] = [50000,60000,90000]
print(df)

      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   90000

In [219]:
# 2. Mengganti Nama Kolom dalam DataFrame
df = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df = df.rename(columns={'A':'X','B':'Y','C':'Z'})
print(df)

   X  Y  Z
0  1  4  7
1  2  5  8
2  3  6  9

### 8. Menangani Data yang Hilang di Pandas

In [220]:
# 1. Mengidentifikasi Data yang Hilang dengan Pandas
import numpy as np
df = pd.DataFrame({'Col1': [1, 2, np.nan],'Col2': [3, np.nan, np.nan]})

print(df.isnull())

    Col1   Col2
0  False  False
1  False   True
2   True   True

In [221]:
# 2. Mengisi Data yang Hilang:
df = df.fillna(0)
print(df.isnull())

    Col1   Col2
0  False  False
1  False  False
2  False  False

In [222]:
# 3. Menghapus Data yang Hilang dengan Pandas
data = {'Name': ['Alice', 'Bob', None], 'Age': [25, None, 35]}
df= pd.DataFrame(data)
df_dropped = df.dropna()

print(df_dropped)

    Name   Age
0  Alice  25.0

### 9. Agregasi dan Pengelompokan dengan Pandas

In [223]:
data = {'Category': ['A', 'B', 'A', 'B'], 'Value': [10, 20, 30, 40]}
df = pd.DataFrame(data)

grouped_sum = df.groupby('Category').sum()
print(f"Sum:\n {grouped_sum}")

grouped_mean = df.groupby('Category').mean()
print(f"Mean:\n {grouped_mean}")

grouped_agg = df.groupby('Category').agg(['sum','mean'])
print(f"Aggregated:\n {grouped_agg}")

Sum:
           Value
Category
A            40
B            60
Mean:
           Value
Category
A          20.0
B          30.0
Aggregated:
          Value
           sum  mean
Category
A           40  20.0
B           60  30.0

### 10. Menggabungkan dan Menyusun Data di Pandas

In [224]:
# 1. Menggabungkan DataFrame
data1 = {
    'Name': ['Alice', 'Charlie', 'Edward', 'Grace'],
    'Years_Experience': [2, 3, 4, 6]
}
df1 = pd.DataFrame(data1)

data2 = {
    'Name': ['Alice', 'Charlie', 'Frank', 'Grace'],
    'Role': ['Manager', 'Analyst', 'Developer', 'HR']
}
df3 = pd.DataFrame(data2)

df_merged_inner = pd.merge(df1,df3,on='Name',how='inner')
df_merged_outer = pd.merge(df1,df3,on='Name',how='outer')
df_merged_left = pd.merge(df1,df3,on='Name',how='left')
df_merged_right = pd.merge(df1,df3,on='Name',how='right')

print(f"\nInner merge (Intersection of Names):\n {df_merged_inner}")
print(f"\nOuter Merge (Union of Names):\n {df_merged_outer}")
print(f"\nLeft Merge (Left of Names):\n {df_merged_left}")
print(f"\nRight Merge (Right of Names):\n {df_merged_right}")

Inner merge (Intersection of Names):
       Name  Years_Experience     Role
0    Alice                 2  Manager
1  Charlie                 3  Analyst
2    Grace                 6       HR

Outer Merge (Union of Names):
       Name  Years_Experience       Role
0    Alice               2.0    Manager
1  Charlie               3.0    Analyst
2   Edward               4.0        NaN
3    Frank               NaN  Developer
4    Grace               6.0         HR

Left Merge (Left of Names):
       Name  Years_Experience     Role
0    Alice                 2  Manager
1  Charlie                 3  Analyst
2   Edward                 4      NaN
3    Grace                 6       HR

Right Merge (Right of Names):
       Name  Years_Experience       Role
0    Alice               2.0    Manager
1  Charlie               3.0    Analyst
2    Frank               NaN  Developer
3    Grace               6.0         HR

In [225]:
# 2. Menggabungkan Data vertikal
df = pd.DataFrame({
    'Name': ['Alice', 'Charlie', 'Edward', 'Grace'],
    'Years_Experience': [2, 3, 4, 6],
    'Role': ['Manager', 'Analyst', 'Developer', 'HR']
})
new_df = pd.DataFrame({
    'Name': ['John', 'Lily'],
    'Years_Experience': [5, 3],
    'Role': ['Designer', 'Developer']
})
concated_df = pd.concat([df,new_df],ignore_index=True)

print("Conatenated Dataframe:\n")
print(concated_df)

Conatenated Dataframe:

      Name  Years_Experience       Role
0    Alice                 2    Manager
1  Charlie                 3    Analyst
2   Edward                 4  Developer
3    Grace                 6         HR
4     John                 5   Designer
5     Lily                 3  Developer

### 11. Membentuk Ulang Data di Pandas

In [226]:
# 1. Tabel Pivot
data = {'Date': ['2024-10-03', '2024-10-01', '2024-10-02', '2024-10-02'],'Category': ['A', 'B', 'A', 'B'],'Values': [10, 20, 15, 25]}
df = pd.DataFrame(data)

pivot_table = df.pivot_table(values='Values',index='Date',columns='Category')
print(pivot_table)

Category       A     B
Date
2024-10-01   NaN  20.0
2024-10-02  15.0  25.0
2024-10-03  10.0   NaN

In [227]:
# 2. Penggabungan (Melting)
data = {
    'Date': ['2024-10-01', '2024-10-01', '2024-10-02', '2024-10-02'],
    'Category_A': [10, None, 15, None],
    'Category_B': [None, 20, None, 25]
}
df = pd.DataFrame(data)

melt_df = df.melt(id_vars='Date',var_name='Kategori',value_name='Nilai')
melt_df

         Date    Kategori  Nilai
0  2024-10-01  Category_A   10.0
1  2024-10-01  Category_A    NaN
2  2024-10-02  Category_A   15.0
3  2024-10-02  Category_A    NaN
4  2024-10-01  Category_B    NaN
5  2024-10-01  Category_B   20.0
6  2024-10-02  Category_B    NaN
7  2024-10-02  Category_B   25.0

In [228]:
# 3. Menumpuk dan Membongkar Tumpukan dengan Pandas
data = {
    ('Sales', 'Q1'): [100, 150],
    ('Sales', 'Q2'): [200, 250],
    ('Expenses', 'Q1'): [50, 70],
    ('Expenses', 'Q2'): [80, 90]
}
index = ['Product_A','Product_B']
df = pd.DataFrame(data,index=index)
print(df)

staked_df = df.stack()
print(f"\nStaked:\n {staked_df}")

unstaked_df = staked_df.unstack()
print(f"\nUnstaked:\n {unstaked_df}")

          Sales      Expenses
             Q1   Q2       Q1  Q2
Product_A   100  200       50  80
Product_B   150  250       70  90

Staked:
               Sales  Expenses
Product_A Q1    100        50
          Q2    200        80
Product_B Q1    150        70
          Q2    250        90

Unstaked:
           Sales      Expenses
             Q1   Q2       Q1  Q2
Product_A   100  200       50  80
Product_B   150  250       70  90

C:\Users\HP\AppData\Local\Temp\ipykernel_18972\1406538482.py:12: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  staked_df = df.stack()

### 12. Mengelola Kumpulan Data Besar dengan Pandas

#### 1. Cara memotong-potong baris file agar hemat memory

In [229]:
# 1. membuat data kedalam bentuk potongan-potongan
for chunk in pd.read_csv('../0.Dataset/data_salary_rice_50000.csv',chunksize=10000):
    print(chunk.shape)

(10000, 4)
(10000, 4)
(10000, 4)
(10000, 4)
(10000, 4)

In [230]:
# Memuat file berukuran besar dalam bagian-bagian yang lebih kecil kecil
# for chunk in pd.read_csv('../0.Dataset/data_salary_rice_50000.csv',chunksize=10000):
#     chunk.to_csv('potongan_data_salary_rice.csv',index=False,mode='a',header=False)

In [231]:
#mengambil colom dataset
colums = pd.read_csv('../0.Dataset/data_salary_rice_50000.csv',nrows=0).columns
print(colums)

Index(['id', 'employee_name', 'salary_rice_kg', 'allowance_value_idr'], dtype='object')

#### 2. Manajemen Memori pandas

In [232]:
# meneukan penggunaan memori
df = pd.read_csv('../0.Dataset/data_salary_rice_50000.csv')
df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 4 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   50000 non-null  int64
 1   employee_name        50000 non-null  object
 2   salary_rice_kg       50000 non-null  int64
 3   allowance_value_idr  50000 non-null  int64
dtypes: int64(3), object(1)
memory usage: 4.0 MB

In [233]:
#melihat jumlah pemakaian memori
df.memory_usage()

Index                     132
id                     400000
employee_name          400000
salary_rice_kg         400000
allowance_value_idr    400000
dtype: int64

In [234]:
#Mengubah kolom numerik ke tipe data yang lebih kecil:
data = df.copy()
numerik_colom = ['salary_rice_kg','allowance_value_idr']

sebelum = data[numerik_colom].memory_usage()

data[numerik_colom]=data[numerik_colom].astype('int16')
sesudah = data[numerik_colom].memory_usage()

print(f"Sebelum:\n {sebelum}")
print(f"Sesudah:\n {sesudah}")

Sebelum:
 Index                     132
salary_rice_kg         400000
allowance_value_idr    400000
dtype: int64
Sesudah:
 Index                     132
salary_rice_kg         100000
allowance_value_idr    100000
dtype: int64

In [239]:
# memakai kolom tertentu
print("\nsebelum Filter:")
df.info(verbose=False,memory_usage='deep')
data =df[['allowance_value_idr']].copy()

print("\nsesudah Filter:")
data.info(verbose=False,memory_usage='deep')

sebelum Filter:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Columns: 4 entries, id to allowance_value_idr
dtypes: int64(3), object(1)
memory usage: 4.0 MB

sesudah Filter:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Columns: 1 entries, allowance_value_idr to allowance_value_idr
dtypes: int64(1)
memory usage: 390.8 KB

In [246]:
#mengahpus kolom tertentu
print("\nsebelum hapus colom:")
df.info(verbose=False,memory_usage='deep')

data = df.copy()
del data['id']

print("\nsesudah hapus colom:")
data.info(verbose=False,memory_usage='deep')

sebelum hapus colom:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Columns: 4 entries, id to allowance_value_idr
dtypes: int64(3), object(1)
memory usage: 4.0 MB

sesudah hapus colom:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Columns: 3 entries, employee_name to allowance_value_idr
dtypes: int64(2), object(1)
memory usage: 3.6 MB

In [250]:
# mengimpor data secara bertahap
data = pd.read_csv('../0.Dataset/data_salary_rice_50000.csv',chunksize=10000)
df = pd.concat(data)
df.info(verbose=False,memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Columns: 4 entries, id to allowance_value_idr
dtypes: int64(3), object(1)
memory usage: 4.0 MB