In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../0.dataset/dataset_karyawan_1000.csv')
df.head(10)

,ID_Karyawan,Jenis_Kelamin,Departemen,Status_Pernikahan,Pendidikan_Terakhir,Level_Jabatan,Rating_Kinerja
0,EMP-0001,Laki-laki,IT,Belum Menikah,S1,Mid-Level,Baik
1,EMP-0002,Perempuan,Finance,Belum Menikah,S1,Senior,Baik
2,EMP-0003,Perempuan,Operations,Menikah,D3,Senior,Sangat Baik
3,EMP-0004,Perempuan,Marketing,Belum Menikah,S1,Junior,Baik
4,EMP-0005,Laki-laki,Operations,Belum Menikah,S1,Junior,Sangat Baik
5,EMP-0006,Laki-laki,Marketing,Menikah,S1,Junior,Cukup
6,EMP-0007,Laki-laki,Marketing,Menikah,S2,Junior,Baik
7,EMP-0008,Perempuan,Operations,Menikah,SMA/SMK,Mid-Level,Baik
8,EMP-0009,Perempuan,IT,Belum Menikah,S1,Mid-Level,Cukup
9,EMP-0010,Perempuan,Finance,Menikah,SMA/SMK,Junior,Baik

In [3]:
colom_kategori = df.select_dtypes(include='object').drop(columns=['ID_Karyawan']).columns

## 1.One-Hot Encoding

### 1.Simple One-Hot Encoding

In [4]:
from sklearn.preprocessing import OneHotEncoder
df_target = df.copy()

encoder = OneHotEncoder(sparse_output=False,drop=None)
encoded_features = encoder.fit_transform(df_target[colom_kategori])
encoded_df = pd.DataFrame(encoded_features,columns=encoder.get_feature_names_out(colom_kategori))

encoded_df.head(5)

,Jenis_Kelamin_Laki-laki,Jenis_Kelamin_Perempuan,Departemen_Finance,Departemen_HR,Departemen_IT,Departemen_Marketing,Departemen_Operations,Status_Pernikahan_Belum Menikah,Status_Pernikahan_Cerai,Status_Pernikahan_Menikah,...,Pendidikan_Terakhir_S2,Pendidikan_Terakhir_SMA/SMK,Level_Jabatan_Junior,Level_Jabatan_Lead/Manager,Level_Jabatan_Mid-Level,Level_Jabatan_Senior,Rating_Kinerja_Baik,Rating_Kinerja_Cukup,Rating_Kinerja_Kurang,Rating_Kinerja_Sangat Baik
0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
2,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
3,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

### 2.One-Hot Encoding dengan Drop First

In [5]:
df_target = df.copy()

df_target = pd.get_dummies(df_target,columns=colom_kategori,dtype=int)
df_target.head()

,ID_Karyawan,Jenis_Kelamin_Laki-laki,Jenis_Kelamin_Perempuan,Departemen_Finance,Departemen_HR,Departemen_IT,Departemen_Marketing,Departemen_Operations,Status_Pernikahan_Belum Menikah,Status_Pernikahan_Cerai,...,Pendidikan_Terakhir_S2,Pendidikan_Terakhir_SMA/SMK,Level_Jabatan_Junior,Level_Jabatan_Lead/Manager,Level_Jabatan_Mid-Level,Level_Jabatan_Senior,Rating_Kinerja_Baik,Rating_Kinerja_Cukup,Rating_Kinerja_Kurang,Rating_Kinerja_Sangat Baik
0,EMP-0001,1,0,0,0,1,0,0,1,0,...,0,0,0,0,1,0,1,0,0,0
1,EMP-0002,0,1,1,0,0,0,0,1,0,...,0,0,0,0,0,1,1,0,0,0
2,EMP-0003,0,1,0,0,0,0,1,0,0,...,0,0,0,0,0,1,0,0,0,1
3,EMP-0004,0,1,0,0,0,1,0,1,0,...,0,0,1,0,0,0,1,0,0,0
4,EMP-0005,1,0,0,0,0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,1

## 2.Label Encoding

### 1.Label Encoding Sederhana

In [6]:
from sklearn.preprocessing import LabelEncoder
df_target = df.copy()

label = LabelEncoder()

for col in colom_kategori:
    df_target[col] = label.fit_transform(df_target[col])

df_target[colom_kategori].head()

,Jenis_Kelamin,Departemen,Status_Pernikahan,Pendidikan_Terakhir,Level_Jabatan,Rating_Kinerja
0,0,2,0,1,2,0
1,1,0,0,1,3,0
2,1,4,2,0,3,3
3,1,3,0,1,0,0
4,0,4,0,1,0,3

### 2.Label Encoding Berdasarkan Frekuensi

In [7]:
df_target = df.copy()

for col in colom_kategori:
    frequnecy = df_target[col].value_counts()
    df_target[col] = df_target[col].map(frequnecy)

df_target[colom_kategori].head()

,Jenis_Kelamin,Departemen,Status_Pernikahan,Pendidikan_Terakhir,Level_Jabatan,Rating_Kinerja
0,559,296,398,551,349,546
1,441,145,398,551,168,546
2,441,258,542,218,168,153
3,441,212,398,551,413,546
4,559,258,398,551,413,153

## 3.Binary Encoding

### 1.Binary Encoding Sederhana

In [18]:
from category_encoders import BinaryEncoder
df_target = df.copy()

encoder = BinaryEncoder(cols=colom_kategori)
encoded_data = encoder.fit_transform(df_target[colom_kategori])

encoded_data.head(5)

,Jenis_Kelamin_0,Jenis_Kelamin_1,Departemen_0,Departemen_1,Departemen_2,Status_Pernikahan_0,Status_Pernikahan_1,Pendidikan_Terakhir_0,Pendidikan_Terakhir_1,Pendidikan_Terakhir_2,Level_Jabatan_0,Level_Jabatan_1,Level_Jabatan_2,Rating_Kinerja_0,Rating_Kinerja_1,Rating_Kinerja_2
0,0,1,0,0,1,0,1,0,0,1,0,0,1,0,0,1
1,1,0,0,1,0,0,1,0,0,1,0,1,0,0,0,1
2,1,0,0,1,1,1,0,0,1,0,0,1,0,0,1,0
3,1,0,1,0,0,0,1,0,0,1,0,1,1,0,0,1
4,0,1,0,1,1,0,1,0,0,1,0,1,1,0,1,0

## 4.Ordinal Encoding

### 1.Ordinal Encoding Berdasarkan Urutan Logis

In [19]:
from sklearn.preprocessing import OrdinalEncoder
colom_ordinal = ['Pendidikan_Terakhir','Level_Jabatan']
df_target = df[colom_ordinal].copy()

urutan_akademik = ['SMA/SMK','D3','S1','S2']
urutan_jabatan = ['Junior','Mid-Level','Senior','Lead/Manager']

df_target['Level_Jabatan'].unique()
encoder = OrdinalEncoder(categories=[urutan_akademik,urutan_jabatan],dtype=int)

df_target[colom_ordinal] = encoder.fit_transform(df_target[colom_ordinal])

df_target.head()

   Pendidikan_Terakhir  Level_Jabatan
0                    2              1
1                    2              2
2                    1              2
3                    2              0
4                    2              0

## 5.Frequency Encoding

### 1.Frequency Encoding Sederhana

In [20]:
df_target = df.copy()

for col in colom_kategori:
    frequnecy = df_target[col].value_counts()
    df_target[col] = df_target[col].map(frequnecy)

df_target[colom_kategori].head()

,Jenis_Kelamin,Departemen,Status_Pernikahan,Pendidikan_Terakhir,Level_Jabatan,Rating_Kinerja
0,559,296,398,551,349,546
1,441,145,398,551,168,546
2,441,258,542,218,168,153
3,441,212,398,551,413,546
4,559,258,398,551,413,153

### 2.Frequency Encoding dengan Normalisasi

In [27]:
df_target = df.copy()
from sklearn.preprocessing import MinMaxScaler

for col in colom_kategori:
    frequnecy = df_target[col].value_counts()
    df_target[col] = df_target[col].map(frequnecy)

scaler = MinMaxScaler()
df_target[colom_kategori]= scaler.fit_transform(df_target[colom_kategori]).round(2)

df_target[colom_kategori].head(5)

,Jenis_Kelamin,Departemen,Status_Pernikahan,Pendidikan_Terakhir,Level_Jabatan,Rating_Kinerja
0,1.0,1.00,0.7,1.00,0.81,1.00
1,0.0,0.27,0.7,1.00,0.29,1.00
2,0.0,0.82,1.0,0.28,0.29,0.21
3,0.0,0.59,0.7,1.00,1.00,1.00
4,1.0,0.82,0.7,1.00,1.00,0.21

## 6.Hash Encoding

### 1.Hash Encoding Sederhana

In [33]:
df_target = df.copy()
from category_encoders import HashingEncoder

encoder = HashingEncoder(cols=colom_kategori,n_components=3)
df_target = encoder.fit_transform(df_target)

df_target.head(5)

   col_0  col_1  col_2 ID_Karyawan
0      1      2      3    EMP-0001
1      1      3      2    EMP-0002
2      1      1      4    EMP-0003
3      3      2      1    EMP-0004
4      2      1      3    EMP-0005

### 2.Hash Encoding dengan Collision Handling

In [36]:
df_target = df.copy()
from category_encoders import HashingEncoder

encoder = HashingEncoder(cols=colom_kategori,n_components=16)
df_target = encoder.fit_transform(df_target)

df_target.head()

,col_0,col_1,col_2,col_3,col_4,col_5,col_6,col_7,col_8,col_9,col_10,col_11,col_12,col_13,col_14,col_15,ID_Karyawan
0,1,0,0,1,0,0,0,0,0,0,0,0,3,0,0,1,EMP-0001
1,2,0,0,1,1,0,0,0,0,0,0,0,2,0,0,0,EMP-0002
2,0,1,1,1,1,0,0,0,1,0,0,0,0,1,0,0,EMP-0003
3,2,0,0,0,1,0,0,0,0,0,0,1,2,0,0,0,EMP-0004
4,1,0,1,0,0,0,0,0,0,0,0,0,2,1,0,1,EMP-0005