In [67]:
import pandas as pd
import numpy as np

## 1.Ekstraksi Fitur dari Data Waktu

In [68]:

jumlah_baris = 15

# 1. Tentukan tanggal awal sebagai acuan
start_date = pd.to_datetime('2026-01-01 08:00:00')

# 2. Buat acakan "jarak hari" (0 sampai 365 hari) dan "jarak jam" (0 sampai 23 jam)
acak_hari = np.random.randint(0, 365, size=jumlah_baris)
acak_jam = np.random.randint(0, 24, size=jumlah_baris)

# 3. Tambahkan rentang acak tersebut ke tanggal awal
timestamp_acak = start_date + pd.to_timedelta(acak_hari, unit='D') + pd.to_timedelta(acak_jam, unit='h')

data = {
    'timestamp': timestamp_acak,
    'value': [i for i in range(jumlah_baris)]
}

df = pd.DataFrame(data)
df.head()

            timestamp  value
0 2026-12-05 07:00:00      0
1 2026-11-02 22:00:00      1
2 2026-12-18 04:00:00      2
3 2026-04-29 18:00:00      3
4 2026-07-06 09:00:00      4

### 1.Ekstraksi Fitur Berbasis Waktu (Hari, Bulan, Tahun)

In [69]:
df_target = df.copy()

df_target['day'] = df_target['timestamp'].dt.day
df_target['month'] = df_target['timestamp'].dt.month
df_target['year'] = df_target['timestamp'].dt.year

df_target.head()

            timestamp  value  day  month  year
0 2026-12-05 07:00:00      0    5     12  2026
1 2026-11-02 22:00:00      1    2     11  2026
2 2026-12-18 04:00:00      2   18     12  2026
3 2026-04-29 18:00:00      3   29      4  2026
4 2026-07-06 09:00:00      4    6      7  2026

### 2.Ekstraksi Fitur Tren

In [70]:
df_target = df.copy()
df_target['trend'] = df_target['value'].rolling(window=3).mean()
df_target['trend'] = df_target['trend'].fillna(0)
df_target.head()

            timestamp  value  trend
0 2026-12-05 07:00:00      0    0.0
1 2026-11-02 22:00:00      1    0.0
2 2026-12-18 04:00:00      2    1.0
3 2026-04-29 18:00:00      3    2.0
4 2026-07-06 09:00:00      4    3.0

### 3.Ekstraksi Fitur Hari Libur

In [73]:
from holidays import Indonesia

id_holidays = Indonesia()
df_target = df.copy()
df_target['is_holiday'] = df_target['timestamp'].dt.date.isin(id_holidays)
df_target.head()

            timestamp  value  is_holiday
0 2026-12-05 07:00:00      0       False
1 2026-11-02 22:00:00      1       False
2 2026-12-18 04:00:00      2       False
3 2026-04-29 18:00:00      3       False
4 2026-07-06 09:00:00      4       False

### 3.Ekstraksi Fitur Weekday vs Weekend

In [79]:
df_target = df.copy()
df_target['id_weekend'] = np.where(df_target['timestamp'].dt.weekday >=5 , 'Weekend','Weekday')
df_target.head()

            timestamp  value id_weekend
0 2026-12-05 07:00:00      0    Weekend
1 2026-11-02 22:00:00      1    Weekday
2 2026-12-18 04:00:00      2    Weekday
3 2026-04-29 18:00:00      3    Weekday
4 2026-07-06 09:00:00      4    Weekday